# docker-compose.yml
version: '3'

networks:
  nairobi-net:
    driver: bridge

services:
  nairobi:
    build:
      context: .
      dockerfile: apps/nairobi/Dockerfile
    networks:
      - nairobi-net
    ports:
      - 2101:80

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    networks:
      - nairobi-net

  database:
    image: 'postgres' # use latest official postgres version
    environment:
      - POSTGRES_USER=unicorn_user
      - POSTGRES_PASSWORD=magical_password
      - POSTGRES_DB=nairobi
    networks:
      - nairobi-net
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down

  # pgadmin:
  #   image: 'dpage/pgadmin4'
  #   networks:
  #     - nairobi-net
  #   ports:
  #     - 81:80
  #   environment:
  #     - 'PGADMIN_DEFAULT_EMAIL=user@domain.com'
  #     - 'PGADMIN_DEFAULT_PASSWORD=SuperSecret'

volumes:
  database-data: # named volumes can be managed easier using docker-compose
