# docker-compose.yml
version: '3'
services:
  database:
    image: 'postgres' # use latest official postgres version
    environment:
      - POSTGRES_USER=unicorn_user
      - POSTGRES_PASSWORD=magical_password
      - POSTGRES_DB=nairobi
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down

  pgadmin:
    image: 'dpage/pgadmin4'
    ports:
      - 80:80
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=user@domain.com'
      - 'PGADMIN_DEFAULT_PASSWORD=SuperSecret'

volumes:
  database-data: # named volumes can be managed easier using docker-compose
